### ISSUE TITLE
Images shoot errors with content:fields.mdx configuration

### ISSUE THREAD

**Issue by f33w** [Thinkmill/keystatic#1043]
I've created Astro project through the Keystatic CLI, then configured Keystatic to use **content:fields.mdx**, but when I am adding images to post through admin panel they fire errors when I am previewing page in **dev mode**. 

How the image line code looks in mdx file:
`![asd](purple-portal.png)`

**The error:**
```
Error
An error occurred.
Cannot find module 'purple-portal.png' imported from '/Users/sota/myBlogFolder/src/content/posts/post-1.mdx'
Stack Trace
Error: Cannot find module 'purple-portal.png' imported from '/Users/sota/myBlogFolder/src/content/posts/post-1.mdx'
    at nodeImport (file:///Users/sota/myBlogFolder/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55037:25)
    at ssrImport (file:///Users/sota/myBlogFolder/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:30)
    at eval (/Users/sota/myBlogFolder/src/content/posts/post-1.mdx:6:37)
    at async instantiateModule (file:///Users/sota/myBlogFolder/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9)
```

**My keystatic config:**
```
import { config, fields, collection } from '@keystatic/core';

export default config({
  storage: {
    kind: 'local',
  },
  collections: {
    posts: collection({
      label: 'Posts',
      slugField: 'title',
      path: 'src/content/posts/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: {
           label: 'Title',
           description: 'modifies meta, SERP, OG',
           validation: {
            isRequired: true,
            length: { min: 58 } } 
          } }),
        description: fields.text({
          label: 'Description',
          multiline: true,
          validation: {
            isRequired: true,
            length: { min: 150, max: 160 } },
        }),
        pubDate: fields.date({ label: 'Pub Date', defaultValue: { kind: "today" }, validation: { isRequired: true } }),
        lastMod: fields.date({ label: 'Last mod', defaultValue: { kind: "today" }, validation: { isRequired: true }}),
        articleSection: fields.text({ label: 'Article section', description: 'modifies OG', defaultValue: 'retirement', validation: { isRequired: true }, }),
        content: fields.mdx ({ label: 'Content' }),
      },
    }),
    authors: collection({
      label: 'Authors',
      slugField: 'name',
      path: 'src/content/authors/*',
      schema: {
        name: fields.slug({ name: { label: 'Name' } }),
      }
    })
  },
});
```

**Comment by f33w** [comment]
UPD: I found the solution. For everybody with the same issue, you must specify the path to images like so:
```
content: fields.mdx ({
          label:'Content',
          options:{
            image: {
              directory: 'src/content/posts/',
              publicPath: '../'
            }
          }
        }),
```

In this case images will be saved in the **src/content/{POST_SLUG}/**, that is handy if you have configured your path to posts as so:
```
...
collections: {
    posts: collection({
      label: 'Posts',
      slugField: 'title',
      path: 'src/content/posts/*/',
      format: { contentField: 'content' },
...
```
This way both mdx file and images will be in the same folder.
