### ISSUE TITLE
Can't build on cloudflare

### ISSUE THREAD

**Issue by iamyuu** [Thinkmill/keystatic#431]
Hey, this library is a great idea, but I'm having trouble deploying to [Cloudflare Pages](https://pages.cloudflare.com/), see the error log. I'm using Astro and GitHub as storage btw.

<details>

<summary>Error Log</summary>

```sh
✘ [ERROR] Could not resolve "fs/promises"

    ../../node_modules/@keystatic/core/api/generic/dist/keystatic-core-api-generic.cjs.js:8:17:
      8 │ var fs = require('fs/promises');
        ╵                  ~~~~~~~~~~~~~

  The package "fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "node:crypto"

    ../../node_modules/@keystatic/core/api/generic/dist/keystatic-core-api-generic.cjs.js:9:26:
      9 │ var node_crypto = require('node:crypto');
        ╵                           ~~~~~~~~~~~~~

  The package "node:crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    ../../node_modules/@keystatic/core/api/generic/dist/keystatic-core-api-generic.cjs.js:13:19:
      13 │ var path = require('path');
         ╵                    ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    ../../node_modules/@keystatic/core/api/generic/dist/keystatic-core-api-generic.cjs.js:17:8:
      17 │ require('crypto');
         ╵         ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    ../../node_modules/@hapi/iron/lib/index.js:3:23:
      3 │ const Crypto = require('crypto');
        ╵                        ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs/promises"

    ../../node_modules/@keystatic/core/dist/read-local-ecc50d5b.cjs.js:3:17:
      3 │ var fs = require('fs/promises');
        ╵                  ~~~~~~~~~~~~~

  The package "fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    ../../node_modules/@hapi/cryptiles/lib/index.js:3:23:
      3 │ const Crypto = require('crypto');
        ╵                        ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    ../../node_modules/@keystatic/core/dist/read-local-ecc50d5b.cjs.js:4:19:
      4 │ var path = require('path');
        ╵                    ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "stream"

    ../../node_modules/@hapi/b64/lib/encoder.js:9:23:
      9 │ const Stream = require('stream');
        ╵                        ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "stream"

    ../../node_modules/@hapi/b64/lib/decoder.js:9:23:
      9 │ const Stream = require('stream');
        ╵                        ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs/promises"

    ../../node_modules/@keystatic/core/reader/dist/keystatic-core-reader.cjs.js:24:17:
      24 │ var fs = require('fs/promises');
         ╵                  ~~~~~~~~~~~~~

  The package "fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    ../../node_modules/@keystatic/core/reader/dist/keystatic-core-reader.cjs.js:25:19:
      25 │ var path = require('path');
         ╵                    ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    ../../node_modules/@keystatic/core/dist/read-local-ecc50d5b.cjs.js:7:21:
      7 │ var crypto = require('crypto');
        ╵                      ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 error   Could not resolve "stream"
  File:
    ../../node_modules/@hapi/b64/lib/decoder.js:9:23
  Code:
    > 9 | const Stream = require('stream');
         |                       ^
      12 | const internals = {
  Stacktrace:
Error: Build failed with 13 errors:
../../node_modules/@hapi/b64/lib/decoder.js:9:23: ERROR: Could not resolve "stream"
../../node_modules/@hapi/b64/lib/encoder.js:9:23: ERROR: Could not resolve "stream"
../../node_modules/@hapi/cryptiles/lib/index.js:3:23: ERROR: Could not resolve "crypto"
../../node_modules/@hapi/iron/lib/index.js:3:23: ERROR: Could not resolve "crypto"
../../node_modules/@keystatic/core/api/generic/dist/keystatic-core-api-generic.cjs.js:8:17: ERROR: Could not resolve "fs/promises"
...
    at failureErrorWithLog (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:1636:15)
    at /opt/buildhome/repo/node_modules/esbuild/lib/main.js:1048:25
    at /opt/buildhome/repo/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:1046:7)
    at /opt/buildhome/repo/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

</details>

**Comment by JedWatson** [comment]
Hey @iamyuu 

Sorry about this. What's happening is Keystatic currently depends on node packages (including specifically node crypto) that don't work on Cloudflare Workers, which runs Cloudflare Pages website.

We're planning to fix this in the coming weeks and replace those dependencies (or rewrite the code to use different strategies) so Keystatic can be deployed to Workers, but for now you'll need a full node-compatible runtime to run Keystatic.

In the meantime, it's a bit of a hacky workaround, but you _can_ create an additional deployment somewhere like Vercel and _just use that to run Keystatic_ on a domain like `yourapp.vercel.com` for free. Don't actually move your website from Cloudflare Pages or anything, just connect Vercel to your repo, deploy, and use the temporary domain to access Keystatic.

I'll leave this open and add the roadmap label so we update you when Keystatic works on Cloudflare Workers — hopefully not long 🤞

**Comment by JedWatson** [comment]
Hey @iamyuu 

Sorry about this. What's happening is Keystatic currently depends on node packages (including specifically node crypto) that don't work on Cloudflare Workers, which runs Cloudflare Pages website.

We're planning to fix this in the coming weeks and replace those dependencies (or rewrite the code to use different strategies) so Keystatic can be deployed to Workers, but for now you'll need a full node-compatible runtime to run Keystatic.

In the meantime, it's a bit of a hacky workaround, but you _can_ create an additional deployment somewhere like Vercel and _just use that to run Keystatic_ on a domain like `yourapp.vercel.com` for free. Don't actually move your website from Cloudflare Pages or anything, just connect Vercel to your repo, deploy, and use the temporary domain to access Keystatic.

I'll leave this open and add the roadmap label so we update you when Keystatic works on Cloudflare Workers — hopefully not long 🤞

**Comment by JedWatson** [comment]
Oh also... let's add this limitation to the docs so it doesn't confuse anybody else before we get it fixed

**Comment by iamyuu** [comment]
Yeah, the problem is that Cloudflare is not fully compatible with Node.js packages

What about separating the storage package? The core package will write abstraction, and the storage package will implement that, so if the devs use GitHub as storage, the reader API will be not available anymore

```js
import { config } from '@keystatic/core';
import { github } from '@keystatic/github-storage';

export default config({
  storage: github({
    repo: {
      owner: 'Thinkmill',
      name: 'keystatic',
    },
  },
});
```

**Comment by rozenmd** [comment]
Ah bugger, just ran into this too. 

Was surprised since Astro normally works on Pages and just assumed plugins for it would as well.

**Comment by rozenmd** [comment]
This is awesome, cheers @emmatown !!
