### ISSUE TITLE
npm run build fails with hybrid-adapter-missing error after first create

### ISSUE THREAD

**Issue by pkellner** [Thinkmill/keystatic#964]
I actually have followed all the directions trying to both update my blog project, as well as a new keystatic install following the steps [here](https://docs.astro.build/en/guides/cms/keystatic/). I get the same error that I get when I just do these two steps:

```
npm create @keystatic@latest
npm install
npm run build
```

`npm run dev` works with no issue as expected.

My versions:
  OSX 14.2.1
  NPM: 10.2.3
  NODE: 20.10.0

Here is the error:  

```
peterkellner@PKMBOOKPROM3-2 new-keystatic-project % npm run build
 
> @keystatic/templates-astro@0.0.15 build
> astro build
 
05:26:07 [vite] Re-optimizing dependencies because vite config has changed
05:26:07 Types generated 118ms
05:26:07 [build] output: "hybrid"
05:26:07 [build] directory: /Users/peterkellner/Downloads/bug/new-keystatic-project/dist/
05:26:07 [build] Collecting build info...
05:26:07 [build] ✓ Completed in 125ms.
[NoAdapterInstalled] Cannot use `output: 'server'` or `output: 'hybrid'` without an adapter. Please install and configure the appropriate server adapter for your final deployment.
  Hint:
    See https://docs.astro.build/en/guides/server-side-rendering/ for more information.
  Error reference:
    https://docs.astro.build/en/reference/errors/no-adapter-installed/
  Stack trace:
    at viteBuild (file:///Users/peterkellner/Downloads/bug/new-keystatic-project/node_modules/astro/dist/core/build/static-build.js:37:11)
    at async AstroBuilder.run (file:///Users/peterkellner/Downloads/bug/new-keystatic-project/node_modules/astro/dist/core/build/index.js:165:7)
    at async build (file:///Users/peterkellner/Downloads/bug/new-keystatic-project/node_modules/astro/dist/cli/build/index.js:20:3)
    at async cli (file:///Users/peterkellner/Downloads/bug/new-keystatic-project/node_modules/astro/dist/cli/index.js:164:5)
```

**Comment by pkellner** [comment]
I now understand I need an adapter. Might be good if that was mentioned in the docs for those of us that always run "npm run build" just to make sure nothing has broken.
